// <auto-generated>
// ReSharper disable All

using Core.DbModels;
using Microsoft.EntityFrameworkCore.Design;

namespace DatabaseAccess.Data
{
    public class DbContextConnectionFactory : IDesignTimeDbContextFactory<DbContextConnection>
    {
        public DbContextConnection CreateDbContext(string[] args)
        {
            return new DbContextConnection();
        }
    }
}
// </auto-generated>
