// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Core.DbModels
{
    // ****************************************************************************************************
    // This is not a commercial licence, therefore only a few tables/views/stored procedures are generated.
    // ****************************************************************************************************

    // User
    public partial class User
    {
        public int Id { get; set; } // ID (Primary key)
        public string Name { get; set; } // Name (Primary key) (length: 255)
        public string Email { get; set; } // Email (Primary key) (length: 255)
        public Guid? ResetPasswordGuid { get; set; } // ResetPasswordGuid
        public string PasswordHash { get; set; } // PasswordHash (Primary key) (length: 255)
        public string Salt { get; set; } // Salt (Primary key) (length: 255)
        public bool Administrator { get; set; } // Administrator (Primary key)

        public User()
        {
            Administrator = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
